logman create alert "Processor Information\Processor Time" -si 5 -th "\Processor Information(_Total)\%% Processor time > 50"
logman create alert "Processor Information\Privileged Time" -si 5 -th "\Processor Information(_Total)\%% Privileged Time > 20"
logman create alert "Processor Information\Interrupt Time" -si 5 -th "\Processor Information(_Total)\%% Interrupt Time > 10"
logman create alert "Processor Information\DPC Time" -si 5 -th "\Processor Information(_Total)\%% DPC Time > 10"
logman create alert "System Context Switches" -si 5 -th "\System\Context Switches/sec > 2500"
logman create alert "System Processor Queue Length" -si 5 -th "\System\Processor Queue Length > 2"

logman create alert "Memory\Available MBytes" -si 5 -th "\Memory\Available MBytes < 10"
logman create alert "Memory\Free System Page Table Entries" -si 5 -th "\Memory\Free System Page Table Entries < 20000"
logman create alert "Memory\Pool Nonpaged Bytes" -si 5 -th "\Memory\Pool Nonpaged Bytes > 60"
logman create alert "Memory\Pool Paged Bytes" -si 5 -th "\Memory\Pool Paged Bytes > 60"
logman create alert "Paging File\%% Usage" -si 5 -th "\Paging File(_Total)\%% Usage > 70"
logman create alert "Process\Handle Count" -si 5 -th "\Process(_Total)\Handle Count > 100"
logman create alert "Process\Thread Count" -si 5 -th "\Process(_Total)\Thread Count > 100"
logman create alert "Process\Private Bytes" -si 5 -th "\Process(_Total)\Private Bytes > 100"
logman create alert "Process\Working Set" -si 5 -th "\Process(_Total)\Working Set > 100"

logman create alert "LogicalDisk\Free Space" -si 5 -th "\LogicalDisk(_Total)\%% Free Space < 10"
logman create alert "LogicalDisk\Avg. Disk Queue Length" -si 5 -th "\LogicalDisk(_Total)\Avg. Disk Queue Length > 2"
logman create alert "LogicalDisk\Avg. Disk sec/Read" -si 5 -th "\LogicalDisk(_Total)\Avg. Disk sec/Read > 15"
logman create alert "LogicalDisk\Avg. Disk sec/Transfer" -si 5 -th "\LogicalDisk(_Total)\Avg. Disk sec/Transfer > 15"
logman create alert "LogicalDisk\Avg. Disk sec/Write" -si 5 -th "\LogicalDisk(_Total)\Avg. Disk sec/Write > 15"
logman create alert "LogicalDisk\IO Data Operations" -si 5 -th "\Process(_Total)\IO Data Operations/sec > 1000"

logman create alert "Network Interface\Output Queue Length" -si 5 -th "\Network Interface [Replace Network Interface Name]\Output Queue Length > 1"