logman delete "Processor Information"
logman delete "Memory"
logman delete "Paging File"
logman delete "Process"
logman delete "LogicalDisk"
logman delete "Network Interface"

logman delete "Processor Information\Processor Time"
logman delete "Processor Information\Privileged Time"
logman delete "Processor Information\Interrupt Time"
logman delete "Processor Information\DPC Time"
logman delete "System Context Switches"
logman delete "System Processor Queue Length"
logman delete "Memory\Available MBytes"
logman delete "Memory\Free System Page Table Entries"
logman delete "Memory\Pool Nonpaged Bytes"
logman delete "Memory\Pool Paged Bytes"
logman delete "Paging File\%% Usage"
logman delete "Process\Handle Count"
logman delete "Process\Thread Count"
logman delete "Process\Private Bytes"
logman delete "Process\Working Set"
logman delete "LogicalDisk\Free Space"
logman delete "LogicalDisk\Avg. Disk Queue Length"
logman delete "LogicalDisk\Avg. Disk sec/Read"
logman delete "LogicalDisk\Avg. Disk sec/Transfer"
logman delete "LogicalDisk\Avg. Disk sec/Write"
logman delete "LogicalDisk\IO Data Operations"
logman delete "Network Interface\Output Queue Length"
